# Generated by Django 4.2.1 on 2023-05-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_currency_code_alter_currency_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('country', 'code')},
        ),
    ]
