# Generated by Django 4.2.1 on 2023-05-22 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_currency_code_alter_currency_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.currency'),
        ),
    ]
