# Generated by Django 4.2.1 on 2023-05-23 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_accounttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_provider', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('balance', models.IntegerField(default=0)),
                ('last_balance_update', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.accounttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('account_provider', 'account_number', 'account_type')},
            },
        ),
    ]
