# Generated by Django 4.2.1 on 2023-05-26 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='transactionCharge',
            new_name='transaction_charge',
        ),
    ]
