# Generated by Django 4.2.1 on 2023-05-26 09:57

from django.db import migrations, models
import django.db.models.deletion
import expenses.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_account'),
        ('expenses', '0003_rename_transactioncharge_expense_transaction_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narration', models.TextField()),
                ('amount', models.IntegerField(default=0)),
                ('transaction_charge', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('renewal_date', models.CharField(max_length=5, validators=[expenses.validators.RenewalDateValidator('12-31')])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.account')),
                ('tags', models.ManyToManyField(to='expenses.usagetag')),
            ],
        ),
    ]
