# Generated by Django 4.2.1 on 2023-05-26 10:01

from django.db import migrations, models
import expenses.validators


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_recurringpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringpayment',
            name='renewal_date',
            field=models.CharField(help_text='Two digits, 01 | 31, monthly; Four Digits, 12-01, 12-31, annual (month-day).', max_length=5, validators=[expenses.validators.RenewalDateValidator('12-31')]),
        ),
    ]
