# Generated by Django 4.2.1 on 2023-05-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_recurringpayment_renewal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringpayment',
            name='renewal_count',
            field=models.IntegerField(default=0),
        ),
    ]
