# Generated by Django 4.2.1 on 2023-07-06 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_account'),
        ('expenses', '0007_remove_recurringpayment_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DB', 'Debit'), ('CD', 'Credit')], max_length=2)),
                ('amount', models.IntegerField()),
                ('automatic', models.BooleanField(default=False)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_for', models.CharField(blank=True, choices=[('EX', 'Expenses'), ('RP', 'Recurring Payment')], max_length=2, null=True)),
                ('transaction_for_id', models.IntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.account')),
            ],
        ),
    ]
