# Generated by Django 4.2.1 on 2024-07-07 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expenses', '0008_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='account',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='transaction_charge',
        ),
        migrations.RemoveField(
            model_name='recurringpayment',
            name='transaction_charge',
        ),
        migrations.AddField(
            model_name='expense',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_for',
            field=models.CharField(blank=True, choices=[('EX', 'Expense'), ('RP', 'Recurring Payment')], max_length=2, null=True),
        ),
    ]
