# Generated by Django 4.2.1 on 2023-05-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='granted',
            field=models.BooleanField(default=False),
        ),
    ]
